#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

ln -sf "$PWD/.config/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.config/zellij" "$XDG_CONFIG_HOME"/zellij
ln -sf "$PWD/.config/starship.toml" "$XDG_CONFIG_HOME"/starship.toml

packages=(
	rust-fd-find
	ripgrep
	starship
	lazygit
    neovim
)

sudo apt update
sudo apt install $packages

echo "All packages have been installed."
